version: '3.7'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "54326:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./migrations/postgres.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "log_statement=all", "-c", "timezone=UTC"]
