version: '3.7'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sample
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data-volume:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "timezone=UTC"]
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 3g

volumes:
    data-volume: