name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    -
        name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          script: |
            rm -rf ${{ secrets.NAME }}
            ${{ secrets.SCRIPT }} # git clone ...
            cd ${{ secrets.NAME }}
            
            docker-compose -f postgres.docker-compose.yaml stop
            docker compose rm
            docker-compose -f postgres.docker-compose.yaml --compatibility up -d
